### PR TITLE
HPT-687 factories and HPT-704 0.14 update

### PR DESCRIPTION
**Pull request by dlpierce**

### CODE REVIEW

**Comment by andjsmit** [comment]
+1 - All appeared to work for me.

**Comment by aploshay** [comment]
+1, but added another commit with a few minor changes:
- Changed .create to .build calls in after(:build) blocks, so that if you are building an object with relationships, the entire stack is build but not persisted until save
- In :complete_paged_work, removed line that was putting Page 1 in both Chapter 1 and Chapter 2 -- this didn't make sense to me, but maybe it was intentional?
- Removed commented, blank lines

**Comment by dlpierce** [comment]
The purpose of that line in complete_paged_work was just to show that a page could belong to two different sections, like if a chapter did not start at the top of a page.

**Comment by aploshay** [comment]
Tests were passing, but we didn't have full coverage of the new factories.  Added new commit with changes:
- Restored inclusion of Page 1 in Chapter 2, in :complete_paged_work factory
- Added basic model tests for factory objects
- Added check of ENV variables for passing arguments to rspec rake task
  As a result of working with those changes, also added:
- Reverted after(:build) call in Collection factory to after(:work) (as it broke something)
- In Page factory, limit page number to '04' (as we don't have images past this, and the sequence keeps accruing during the same rspec run, currently into the 20s)

**Pull request merged**
