### PR TITLE
HPT-564 Interface area for container hierarchy

### PR DESCRIPTION
**Pull request by randalldfloyd**
Adds a new partial and formatting helpers to consume JSON and then produce an indented list representing the hierarchical structure of containers. Also adds routes for container resources but they currently do not have anywhere to go without container controllers or behaviors.

### CODE REVIEW

**Comment by aploshay** [comment]
@randalldfloyd Hmm, I must be doing something wrong -- `@cont_json` is returning nil for my object, so I'm not seeing the table of contents.  Thoughts?

**Comment by randalldfloyd** [comment]
@aploshay That's right, this story simply called for an interface area and ability to format a structured response. But, there's nowhere to get that structure from currently so when I demo'd I literally pasted a JSON string into @cont_json on the partial to show it in action. The question is where and how to get it from a controller, and where does the controller get it from (dynamically from the membership methods or from something stashed in index.) I will paste the structured JSON in a comment to show what it's expecting...

**Comment by randalldfloyd** [comment]
@aploshay When I demo'd the table of contents partial, I literally stuck this in at the top of `table_of_contents.html.erb`: 

```
@cont_json = '[
         {
             "id": "8823ca44-b3b2-4ea7-bbbc-3b6edd62cf27",
             "title": "Half title page",
             "type": "Container"
         },
         {
             "id": "34b6ab73-a2bd-4f31-9bec-efa0258d4668",
             "title": "The Score",
             "type": "Container"
         },
         [
             {
                 "id": "8db5408c-a4d3-4999-97ce-6d86ee8ae1b1",
                 "title": "I: Allegro con brio",
                 "type": "Container"
             },
             {
                 "id": "3ee21ec3-c0c1-4d8a-93fe-a34086067c92",
                 "title": "II. Allegro",
                 "type": "Container"
             },
             [
             {
                 "id": "8db5408c-a4d3-4999-97ce-6d86ee8ae1b1",
                 "title": "III. More Allegro",
                 "type": "Container"
             },
             {
                 "id": "3ee21ec3-c0c1-4d8a-93fe-a34086067c92",
                 "title": "IV. Even More Allegro",
                 "type": "Container"
             }
         ]
       ]
   ]'
```

**Comment by aploshay** [comment]
@randalldfloyd Thanks!  +1

**Pull request merged**
